<state><case><name>EXAMPLE 4 1</name>
<author>EXAMPLE 4 Type 1 CO2 calculation</author><comment>Type 1a open-system CO2 computation. The solution is
50 mmol/L in NaHCO3 and is in equilibrium with atmospheric CO2.[Alk] = 5 meq/L, -log pCO2 = 3.5 atmospheres. 
The speciation is run at several fixed pH values.Note also the warning message that appears at pH 9.8, alerting the user that the atmospheric pool of CO2 has been exhausted.  Whenever this message appears, the case should be rerun using a higher input total carbonate concentration.</comment>
<ph>9.6</ph>
<toth></toth>
<ea></ea>
<co2PP>3.1622776601683794E-4</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 4 2</name>
<author>Type 1 CO2 calculation</author><comment>Type 1a open-system CO2 computation. The solution is
50 mmol/L in NaHCO3 and is in equilibrium with atmospheric CO2.[Alk] = 5 meq/L, -log pCO2 = 3.5 atmospheres. 
The speciation is run at several fixed pH values.Note also the warning message that appears at pH 9.8, alerting the user that the atmospheric pool of CO2 has been exhausted.  Whenever this message appears, the case should be rerun using a higher input total carbonate concentration.</comment>
<ph>9.61</ph>
<toth></toth>
<ea></ea>
<co2PP>3.1622776601683794E-4</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 4 3</name>
<author>Type 1 CO2 calculation</author><comment>Type 1a open-system CO2 computation. The solution is
50 mmol/L in NaHCO3 and is in equilibrium with atmospheric CO2.[Alk] = 5 meq/L, -log pCO2 = 3.5 atmospheres. 
The speciation is run at several fixed pH values.Note also the warning message that appears at pH 9.8, alerting the user that the atmospheric pool of CO2 has been exhausted.  Whenever this message appears, the case should be rerun using a higher input total carbonate concentration.</comment>
<ph>9.62</ph>
<toth></toth>
<ea></ea>
<co2PP>3.1622776601683794E-4</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 4 4</name>
<author>Type 1 CO2 calculation</author><comment>Type 1a open-system CO2 computation. The solution is
50 mmol/L in NaHCO3 and is in equilibrium with atmospheric CO2.[Alk] = 5 meq/L, -log pCO2 = 3.5 atmospheres. 
The speciation is run at several fixed pH values.Note also the warning message that appears at pH 9.8, alerting the user that the atmospheric pool of CO2 has been exhausted.  Whenever this message appears, the case should be rerun using a higher input total carbonate concentration.</comment>
<ph>9.7</ph>
<toth></toth>
<ea></ea>
<co2PP>3.1622776601683794E-4</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 4 5</name>
<author>Type 1 CO2 calculation</author><comment>Type 1a open-system CO2 computation. The solution is
50 mmol/L in NaHCO3 and is in equilibrium with atmospheric CO2.[Alk] = 5 meq/L, -log pCO2 = 3.5 atmospheres. 
The speciation is run at several fixed pH values.Note also the warning message that appears at pH 9.8, alerting the user that the atmospheric pool of CO2 has been exhausted.  Whenever this message appears, the case should be rerun using a higher input total carbonate concentration.</comment>
<ph>9.8</ph>
<toth></toth>
<ea></ea>
<co2PP>3.1622776601683794E-4</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>50.00345</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><guesses><gIon>l01</gIon>
<guess>0.001584893</guess>
<gUnit>mM</gUnit>
<gIon>m05</gIon>
<guess>0.05011872</guess>
<gUnit>M</gUnit>
</guesses>
<inputConfig>
<calcpH>false</calcpH>
<conRedox>false</conRedox>
<redoxRxn> </redoxRxn>
<conMixed>false</conMixed>
<mixed></mixed>
<imposed> </imposed>
<solidProp>0</solidProp>
<numDis></numDis>
<ionicFixed>1</ionicFixed>
<ionicStrength>0.050</ionicStrength>
<cc>1.0e-4</cc>
<iter>50</iter>
<outputConfig><cap>false</cap>
<compAct>false</compAct>
<concen>false</concen>
<logK>false</logK>
<intAct>false</intAct>
<pp>false</pp>
<progress>true</progress>
<speciation>false</speciation>
</outputConfig>
</state>