<state><case><name>EXAMPLE 5 1</name>
<author>Type 2 CO2 calculation</author><comment>Type 2a open-system CO2 computation.The electroneutral solution contains 3 meq/L Na+, 1 meq/L Cl-,[Alk] = 2 meq/L, pH = 8.8. The speciation is run as a closed system (-log pCO2 = 0.0) at several input CO3 concentrations.  Note that the computed [Alk] agrees with the known value when Ct is 1.93 mmol/L (case no. 2), and the predicted pCO2 is 10^-3.737 atm. The computed charge balance is also zero for case no. 2.
</comment>
<ph>8.80</ph>
<toth></toth>
<ea></ea>
<co2PP>1.0</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>2.99916</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>1.90108</concentration>
<unit>0</unit>
<ion>l03</ion>
<concentration>1</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 5 2</name>
<author>Type 2 CO2 calculation</author><comment>Type 2a open-system CO2 computation.The electroneutral solution contains 3 meq/L Na+, 1 meq/L Cl-,[Alk] = 2 meq/L, pH = 8.8. The speciation is run as a closed system (-log pCO2 = 0.0) at several input CO3 concentrations.  Note that the computed [Alk] agrees with the known value when Ct is 1.93 mmol/L (case no. 2), and the predicted pCO2 is 10^-3.737 atm. The computed charge balance is also zero for case no. 2.
</comment>
<ph>8.80</ph>
<toth></toth>
<ea></ea>
<co2PP>1.0</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>2.99916</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>1.93197</concentration>
<unit>0</unit>
<ion>l03</ion>
<concentration>1</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 5 3</name>
<author>Type 2 CO2 calculation</author><comment>Type 2a open-system CO2 computation.The electroneutral solution contains 3 meq/L Na+, 1 meq/L Cl-,[Alk] = 2 meq/L, pH = 8.8. The speciation is run as a closed system (-log pCO2 = 0.0) at several input CO3 concentrations.  Note that the computed [Alk] agrees with the known value when Ct is 1.93 mmol/L (case no. 2), and the predicted pCO2 is 10^-3.737 atm. The computed charge balance is also zero for case no. 2.
</comment>
<ph>8.80</ph>
<toth></toth>
<ea></ea>
<co2PP>1.0</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>2.99916</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>1.95884</concentration>
<unit>0</unit>
<ion>l03</ion>
<concentration>1</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 5 4</name>
<author>Type 2 CO2 calculation</author><comment>Type 2a open-system CO2 computation.The electroneutral solution contains 3 meq/L Na+, 1 meq/L Cl-,[Alk] = 2 meq/L, pH = 8.8. The speciation is run as a closed system (-log pCO2 = 0.0) at several input CO3 concentrations.  Note that the computed [Alk] agrees with the known value when Ct is 1.93 mmol/L (case no. 2), and the predicted pCO2 is 10^-3.737 atm. The computed charge balance is also zero for case no. 2.
</comment>
<ph>8.80</ph>
<toth></toth>
<ea></ea>
<co2PP>1.0</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>2.99916</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>1.99067</concentration>
<unit>0</unit>
<ion>l03</ion>
<concentration>1</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><guesses><gIon>m05</gIon>
<guess>0.002511886</guess>
<gUnit>mM</gUnit>
<gIon>l03</gIon>
<guess>0.0010</guess>
<gUnit>mM</gUnit>
<gIon>l01</gIon>
<guess>1.0E-4</guess>
<gUnit>mM</gUnit>
</guesses>
<inputConfig>
<calcpH>false</calcpH>
<conRedox>false</conRedox>
<redoxRxn> </redoxRxn>
<conMixed>false</conMixed>
<mixed></mixed>
<imposed> </imposed>
<solidProp>0</solidProp>
<numDis></numDis>
<ionicFixed>1</ionicFixed>
<ionicStrength>0.003</ionicStrength>
<cc>1.0e-4</cc>
<iter>50</iter>
<outputConfig><cap>false</cap>
<compAct>false</compAct>
<concen>false</concen>
<logK>false</logK>
<intAct>false</intAct>
<pp>false</pp>
<progress>true</progress>
<speciation>false</speciation>
</outputConfig>
</state>