<state><case><name>EXAMPLE 7 1</name>
<author>EXAMPLE 7 Type A Redox Rxn</author><comment>An example of a Class A redox reaction using 3 oxidation states of vanadium 
(III, IV, and V). Each case may have a different pH or electron activity. Here V(III) and V(IV) are both metals (code numbers 39and 40), and are handled by the program. Vanadate (V[V]) is a ligand, and must be 'faked' as a hydrolysis product of V(IV).  
The table of log K's contains 10-4 and 10-5 complexes for V(IV) and OH- in the 5th and 6th 'slots', with log K values of 0.00.  These correspond to the two vanadate species H2VO4- and HVO4 -2, respectively,whose activities and concentrations appear in the corresponding locations in the soluble complexes tables.
</comment>
<ph>5.0</ph>
<toth></toth>
<ea>7.943282347242822E-6</ea>
<co2PP></co2PP>
<no2PP></no2PP>
<ion>m40</ion>
<concentration>10</concentration>
<unit>1</unit>
<ion>m39</ion>
<concentration>1</concentration>
<unit>2</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 7 2</name>
<author>EXAMPLE 7 Type A Redox Rxn</author><comment>An example of a Class A redox reaction using 3 oxidation states of vanadium 
(III, IV, and V). Each case may have a different pH or electron activity. Here V(III) and V(IV) are both metals (code numbers 39and 40), and are handled by the program. Vanadate (V[V]) is a ligand, and must be 'faked' as a hydrolysis product of V(IV).  
The table of log K's contains 10-4 and 10-5 complexes for V(IV) and OH- in the 5th and 6th 'slots', with log K values of 0.00.  These correspond to the two vanadate species H2VO4- and HVO4 -2, respectively,whose activities and concentrations appear in the corresponding locations in the soluble complexes tables.
</comment>
<ph>9.0</ph>
<toth></toth>
<ea>125892.54117941661</ea>
<co2PP></co2PP>
<no2PP></no2PP>
<ion>m40</ion>
<concentration>10</concentration>
<unit>1</unit>
<ion>m39</ion>
<concentration>1</concentration>
<unit>2</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 7 3</name>
<author>EXAMPLE 7 Type A Redox Rxn</author><comment>An example of a Class A redox reaction using 3 oxidation states of vanadium 
(III, IV, and V). Each case may have a different pH or electron activity. Here V(III) and V(IV) are both metals (code numbers 39and 40), and are handled by the program. Vanadate (V[V]) is a ligand, and must be 'faked' as a hydrolysis product of V(IV).  
The table of log K's contains 10-4 and 10-5 complexes for V(IV) and OH- in the 5th and 6th 'slots', with log K values of 0.00.  These correspond to the two vanadate species H2VO4- and HVO4 -2, respectively,whose activities and concentrations appear in the corresponding locations in the soluble complexes tables.
</comment>
<ph>9.0</ph>
<toth></toth>
<ea>7.943282347242822E-6</ea>
<co2PP></co2PP>
<no2PP></no2PP>
<ion>m40</ion>
<concentration>10</concentration>
<unit>1</unit>
<ion>m39</ion>
<concentration>1</concentration>
<unit>2</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><case><name>EXAMPLE 7 4</name>
<author>EXAMPLE 7 Type A Redox Rxn</author><comment>An example of a Class A redox reaction using 3 oxidation states of vanadium 
(III, IV, and V). Each case may have a different pH or electron activity. Here V(III) and V(IV) are both metals (code numbers 39and 40), and are handled by the program. Vanadate (V[V]) is a ligand, and must be 'faked' as a hydrolysis product of V(IV).  
The table of log K's contains 10-4 and 10-5 complexes for V(IV) and OH- in the 5th and 6th 'slots', with log K values of 0.00.  These correspond to the two vanadate species H2VO4- and HVO4 -2, respectively,whose activities and concentrations appear in the corresponding locations in the soluble complexes tables.
</comment>
<ph>4.0</ph>
<toth></toth>
<ea>50.11872336272722</ea>
<co2PP></co2PP>
<no2PP></no2PP>
<ion>m40</ion>
<concentration>10</concentration>
<unit>1</unit>
<ion>m39</ion>
<concentration>1</concentration>
<unit>2</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><guesses><gIon>m39</gIon>
<guess>1.0E-9</guess>
<gUnit>nM</gUnit>
<gIon>m40</gIon>
<guess>1.0E-6</guess>
<gUnit>?M</gUnit>
</guesses>
<inputConfig>
<calcpH>false</calcpH>
<conRedox>true</conRedox>
<redoxRxn>26 27 28</redoxRxn>
<conMixed>false</conMixed>
<mixed></mixed>
<imposed> </imposed>
<solidProp>1</solidProp>
<numDis></numDis>
<ionicFixed>0</ionicFixed>
<ionicStrength>0.005</ionicStrength>
<cc>1.0e-4</cc>
<iter>50</iter>
<outputConfig><cap>false</cap>
<compAct>true</compAct>
<concen>true</concen>
<logK>false</logK>
<intAct>false</intAct>
<pp>true</pp>
<progress>true</progress>
<speciation>false</speciation>
</outputConfig>
</state>