<state><case><name>test</name>
<author>ben</author><comment>Bare Bones test example</comment>
<ph>9</ph>
<toth></toth>
<ea></ea>
<co2PP>3E-4</co2PP>
<no2PP></no2PP>
<ion>m05</ion>
<concentration>50</concentration>
<unit>0</unit>
<ion>l01</ion>
<concentration>50</concentration>
<unit>0</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
<salt></salt>
<concentration></concentration>
<unit>1</unit>
</case><guesses><gIon>l01</gIon>
<guess>0.05</guess>
<gUnit>mM</gUnit>
<gIon>m05</gIon>
<guess>50.0</guess>
<gUnit>M</gUnit>
</guesses>
<inputConfig>
<calcpH>false</calcpH>
<conRedox>false</conRedox>
<redoxRxn> </redoxRxn>
<conMixed>false</conMixed>
<mixed></mixed>
<imposed> </imposed>
<solidProp>0</solidProp>
<numDis></numDis>
<ionicFixed>1</ionicFixed>
<ionicStrength>1</ionicStrength>
<cc>1e-4</cc>
<iter>50</iter>
<outputConfig><compAct>false</compAct>
<concen>false</concen>
<logK>false</logK>
<pp>false</pp>
<progress>true</progress>
<speciation>false</speciation>
</outputConfig>
</state>